spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  profiles:
    name: production

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.naver.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PW}
    properties:
      mail:
        debug: true
        smtp.auth: true
        smtp.ssl.enable: true
        smtp.ssl.trust: smtp.naver.com
  data:
    redis:
      repositories:
        enabled: false

jwt:
  secret: ${JWT}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

url:
  s3-email: https://kau-koala.s3.ap-northeast-2.amazonaws.com/email/

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul
