spring:
  profiles:
    name: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_LOCAL}
    username: ${DB_USERNAME_LOCAL}
    password: ${DB_PW_LOCAL}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST_LOCAL}
