name: CI

on:
  push:
    branches:
      - feature/217

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build module-core
        run: ./gradlew :module-core:clean :module-core:build

      - name: Build module-admin
        run: ./gradlew :module-admin:clean :module-admin:bootJar

      - name: Build module-user
        run: ./gradlew :module-user:clean :module-admin:bootJar