name: CI

on:
  push:
    branches:
      - feature/217

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build module-core
        run: ./gradlew :module-core:clean :module-core:build

      - name: Build module-admin
        run: ./gradlew :module-admin:clean :module-admin:bootJar

      - name: Build module-user
        run: ./gradlew :module-user:clean :module-user:bootJar

      - name: Install AWS Elastic Beanstalk CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awsebcli

      - name: Deploy to Elastic Beanstalk (common-admin)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACION_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
        run: |
          cd module-admin
          eb init -p Corretto 17 running on 64bit Amazon Linux 2023/4.3.0 koala-admin --region ap-northeast-2
          eb deploy