name: USER-CI

on:
  pull_request:
    types: [ closed ]
    paths:
      - 'module-core/**'
      - 'module-user/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'prod'

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build module-core
        run: ./gradlew :module-core:clean :module-core:build

      - name: Build module-user
        run: ./gradlew :module-user:clean :module-user:bootJar

      - name: (common-user) Generate user deployment package
        run: |
          mkdir -p user-deploy
          cp module-user/build/libs/*.jar user-deploy/user-application.jar
          cp Procfile user-deploy/Procfile
          cp -r module-user/.ebextensions user-deploy/.ebextensions
          cp -r module-user/.platform user-deploy/.platform
          cd user-deploy && zip -r user-deploy.zip .
      

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACTION_ACCESS_KEY_ID }}
          # git actions key 값에 오타가 나 있으니 주의할 것
          aws_secret_key: ${{ secrets.AWS_ACION_SECRET_ACCESS_KEY }}
          region: 'ap-northeast-2'
          application_name: User-prod
          environment_name: User-prod-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}-${{ github.run_id }}
          use_existing_version_if_available: true # 기존 버전 사용 설정
          deployment_package: user-deploy/user-deploy.zip
          wait_for_environment_recovery: 300